# Generated by Django 3.2.6 on 2021-08-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeinfomodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tripinfo/'),
        ),
    ]
