# Generated by Django 3.2.6 on 2021-08-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebtoonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webtoon_name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='webtoonpage/')),
            ],
        ),
    ]
