# Generated by Django 3.2.6 on 2021-08-17 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webtoonpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtoonmodel',
            name='genre',
            field=models.TextField(choices=[('일상', '일상'), ('개그', '개그'), ('판타지', '판타지'), ('액션', '액션'), ('드라마/순정/감성', '드라마/순정/감성'), ('시대극', '시대극'), ('호러/스릴러', '호러/스릴러')]),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='댓글')),
                ('pub_date', models.DateTimeField()),
                ('comment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webtoonpage.comment')),
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='webtoonpage.webtoonmodel')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
