# Generated by Django 3.2.6 on 2021-08-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoonpage', '0002_auto_20210817_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='writer',
            field=models.CharField(max_length=10),
        ),
    ]
