# Generated by Django 3.1.7 on 2021-05-20 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('must_go', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecommendMustGo',
            new_name='MustGo',
        ),
    ]
