# Generated by Django 3.2.6 on 2021-08-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripinfo', '0003_writeinfomodel_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeinfomodel',
            name='followers',
        ),
    ]
