# Generated by Django 3.1.7 on 2021-08-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripinfo', '0005_auto_20210826_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeinfomodel',
            name='post_hit',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
